"""
This type stub file was generated by pyright.
"""

import abc

class MazeGenAlgo:
    __metaclass__ = abc.ABCMeta
    def __init__(self, h, w) -> None:
        """Maze Generator Algorithm constructor.

        Attributes
        ----------
            h (int): height of maze, in number of hallways
            w (int): width of maze, in number of hallways
            H (int): height of maze, in number of hallways + walls
            W (int): width of maze, in number of hallways + walls
        """
        ...
    
    @abc.abstractmethod
    def generate(self): # -> None:
        ...
    


