"""
This type stub file was generated by pyright.
"""

from cython import compiled
from mazelib.generate.MazeGenAlgo import MazeGenAlgo

if not compiled:
    ...
class Prims(MazeGenAlgo):
    """
    The Prims maze-generating algorithm.

    1. Choose an arbitrary cell from the grid, and add it to some
        (initially empty) set visited nodes (V).
    2. Randomly select a wall from the grid that connects a cell in
        V with another cell not in V.
    3. Add that wall to the Minimal Spanning Tree (MST), and the edge's other cell to V.
    4. Repeat steps 2 and 3 until V includes every cell in G.
    """
    def __init__(self, h, w) -> None:
        ...
    
    def generate(self): # -> _Array[tuple[int, int], signedinteger[_8Bit]]:
        """Highest-level method that implements the maze-generating algorithm.

        Returns
        -------
            np.array: returned matrix
        """
        ...
    


